version: '3'

services:
  web:
    build: .
    command: >
      gunicorn -c gunicorn.py --reload "hello.app:create_app()"
    env_file:
      - '.env'
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
